#yaml plugin metadata

name: PuppetDB source
version: 1.2
rundeckPluginVersion: 1.0
author: Daniel Fernandez (danielfr@cern.ch)
date: 2016/02/25
providers:
        - name: rundeck-puppetdb-nodes
          service: ResourceModelSource
          title: PuppetDB source
          description: Queries PuppetDB to retrieve node definitions from a specific Foreman hostgroup
          resource-format: resourceyaml
          plugin-type: script
          script-interpreter: /usr/bin/python
          script-file: rundeck_puppetdb_nodes.py
          script-args: "-v --apiurl ${config.apiurl} --hostgroup ${config.hostgroup} --username ${config.username} --keytab ${config.keytab} --file ${config.file} --${config.mode} --factlist ${config.factlist}"
          config:
                - name: apiurl
                  type: String
                  title: PuppetDB
                  description: "PuppetDB API URL. Ex: https://my.puppet.db:2525/v3"
                  default: "https://judy.cern.ch:9081/v3"
                  required: true
                - name: hostgroup
                  type: String
                  title: Hostgroup
                  description: "Foreman Hostgroup"
                  required: true
                - name: username
                  type: String
                  title: Username
                  description: "User to connect to PuppetDB"
                  required: true
                - name: keytab
                  type: String
                  title: Keytab
                  description: "Path to user's keytab to authenticate"
                  required: true
                - name: factlist
                  type: String
                  title: Fact list
                  description: "Space-separated list of facts to retrieve for every node"
                  default: "hostname ipaddress"
                  required: false
                - name: mode
                  type: Select
                  title: Mode
                  description: "Prints out/stores on file the list of nodes"
                  default: print
                  values: print,store
                  required: true
                - name: file
                  type: String
                  title: "Output file"
                  description: "Save list of nodes to file (only if 'store' mode selected)"
                  default: "/var/rundeck/projects/${project.name}/etc/resources.yaml"
