#yaml plugin metadata

name: PuppetDB source
version: 3.1.0
rundeckPluginVersion: 1.0
author: Daniel Fernandez, David Moreno Garcia, Philippe Ganz, Nacho Barrientos Arias (nacho.barrientos@cern.ch), Ignacio Coterillo Coz (ignacio.coterillo.coz@cern.ch), Steve Traylen (steve.traylen@cern.ch)
date: 2021/08/04
providers:
        - name: rundeck-puppetdb-nodes
          service: ResourceModelSource
          title: "PuppetDB source"
          description: Queries PuppetDB to retrieve node definitions from a specific Foreman hostgroup
          resource-format: resourceyaml
          plugin-type: script
          script-interpreter: /usr/bin/python3
          script-file: rundeck_puppetdb_nodes.py
          script-args: "-v --apiurl ${config.apiurl} --hostgroup ${config.hostgroup} --krbuser ${config.krbuser} --keytab ${config.keytab}
                       --sshuser ${config.sshuser} --file ${config.file} --${config.mode} --factlist ${config.factlist}"
          config:
                - name: apiurl
                  type: String
                  title: "PuppetDB"
                  description: "PuppetDB API URL. Ex: https://my.puppet.db:2525/v3"
                  default: "https://constable.cern.ch:9081/pdb/query/v4"
                  required: true
                - name: hostgroup
                  type: String
                  title: "Hostgroup"
                  description: "Foreman Hostgroup"
                  required: true
                - name: factlist
                  type: String
                  title: "Fact list"
                  description: "Space-separated list of facts to retrieve for every node"
                  default: "hostname ipaddress"
                  required: false
                - name: krbuser
                  type: String
                  title: "Kerberos User"
                  description: "Kerberos principal (used alongside 'keytab' to connect to PuppetDB)"
                  required: true
                - name: keytab
                  type: String
                  title: "Kerberos Keytab Path"
                  description: "Absolute path to kerberos principal's keytab (used to authenticate & connect to PuppetDB)"
                  default: "/etc/rundeck/{YOUR_KEYTAB}.keytab"
                  required: true
                - name: sshuser
                  type: String
                  title: "SSH User"
                  description: "User Rundeck will use to connect to hosts via SSH"
                  default: "root"
                  required: true
                - name: mode
                  type: Select
                  title: "Executon Mode"
                  description: "Prints out/stores on file the list of nodes"
                  default: print
                  values: print,store
                  required: true
                - name: file
                  type: String
                  title: "Output file"
                  description: "Save list of nodes to file (only if 'store' mode selected)"
                  default: "/var/lib/rundeck/projects/${project.name}/etc/resources.yaml"
